on: workflow_dispatch

name: Publish plugin

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-wasi
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: test
        run: cargo test
      - name: rust target add
        run: |
          rustup target add wasm32-wasi
          rustup target add wasm32-unknown-unknown
      - name: build
        run: make build-lib
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
